[package]
name = "hyperiond"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.0", features = ["yaml"] }
failure = "0.1.5"
futures = "0.1.26"
stream-cancel = "0.4.4"
hyperion = { path = "../hyperion" }
log = "0.4.6"
pretty_env_logger = "0.3.0"
tokio = "0.1.19"
tokio-signal = "0.2.7"
serde_json = "1.0.39"
