[package]
name = "hyperiond"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[dependencies]
clap = { version = "2.33.0", features = ["yaml"] }
failure = "0.1.5"
futures = "0.1.27"
stream-cancel = "0.4.4"
hyperion = { path = "../hyperion" }
log = "0.4.6"
pretty_env_logger = "0.3.0"
tokio = "0.1.20"
tokio-signal = "0.2.7"
regex = "1.1.6"
serde_yaml = "0.8.9"
