[env]
CARGO_MAKE_EXTEND_WORKSPACE_MAKEFILE = "true"

[tasks.package-release]
dependencies = ["build-release"]
command = "tar"
args = [
  "--xform=s|^|hyperion.rs/|",
  "--xform=s|target/release|bin|",
  "--show-transformed",
  "-czvf",
  "hyperion.rs_${CARGO_MAKE_RUST_TARGET_ARCH}-${CARGO_MAKE_RUST_TARGET_ENV}-${CARGO_MAKE_RUST_TARGET_OS}.tar.gz",
  "target/release/hyperiond",
  "scripts",
]
