[package]
name = "hyperion"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.12"
failure = "0.1.5"
futures = "0.1.26"
log = "0.4.6"
palette = "0.4.1"
rlua = "0.16.2"
serde = "1.0.90"
serde_derive = "1.0.90"
serde_json = "1.0.39"
tokio = "0.1.19"
stream-cancel = "0.4.4"
regex = "1.1.6"
base64 = "0.10.1"
prost = "0.5.0"

[build-dependencies]
prost-build = "0.5.0"
