[package]
name = "hyperion"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"
build = "build.rs"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.12"
failure = "0.1.5"
futures = "0.1.27"
log = "0.4.6"
palette = "0.4.1"
rlua = "0.16.3"
serde = "1.0.91"
serde_derive = "1.0.91"
serde_json = "1.0.39"
tokio = "0.1.20"
stream-cancel = "0.4.4"
regex = "1.1.6"
base64 = "0.10.1"
prost = "0.5.0"
serde_yaml = "0.8.9"
humantime = "1.2.0"
circular-queue = "0.2.0"

[build-dependencies]
prost-build = "0.5.0"
