[package]
name = "hyperion"
version = "0.1.0"
authors = ["Vincent Tavernier <vince.tavernier@gmail.com>"]
edition = "2018"

[dependencies]
byteorder = "1.3.1"
bytes = "0.4.11"
failure = "0.1.5"
futures = "0.1.25"
log = "0.4.6"
palette = "0.4.1"
protobuf = "2.3.0"
rlua = "0.16.2"
serde = "1.0.89"
serde_derive = "1.0.89"
serde_json = "1.0.39"
tokio = "0.1.16"
stream-cancel = "0.4.4"

[build-dependencies]
protobuf-codegen-pure = "2.3.0"
