name: docs

on:
  push:
    branches:
      - master

jobs:
  build-docs:
    runs-on: ubuntu-22.04

    permissions:
      contents: write

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Install Protoc
        uses: arduino/setup-protoc@v2

      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo
            target
          key: ${{ runner.os }}-docs-${{ hashFiles('Cargo.lock', 'rust-toolchain') }}
          restore-keys: |
            ${{ runner.os }}-docs-${{ hashFiles('Cargo.lock', 'rust-toolchain') }}
            ${{ runner.os }}-docs-

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          profile: minimal

      - name: Build docs
        uses: actions-rs/cargo@v1
        with:
          command: doc
          args: --no-deps --document-private-items

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: target/doc

# vim: ts=2:sw=2
